/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32h7sxx.h"
#include "TestCodes.h"

int main(void){
	/*Test Functions**********************/

	/*GPIO Driver Test Functions*/
	//Test_001_Led_Toggle();
	//Test_002_Led_Button_Toggle();
	//Test_003_Led_Button_Toggle_IRQ();

	/*I2C Driver Test Functions*/
	//Test_004_I2C_ssd1306();

	/*Ethernet Driver Test Functions*/
	//Test_005_ETH_PHY_ID();
	//Test_006_ETH_DMA_Memory_Init();
	//Test_007_ETH_Raw_Frame_RX();
	//Test_008_ETH_UDP_Payload();

	/*Forza Test*/
	Test_000_ETH_Forza_Test();

    while(1);

    return 0;
}
