/*
 * stm32h7sxx_i2c_driver.h
 *
 *  Created on: Jun 4, 2026
 *      Author: talha
 */

#ifndef INC_STM32H7SXX_I2C_DRIVER_H_
#define INC_STM32H7SXX_I2C_DRIVER_H_

#include "stm32h7sxx.h"
#include <stdint.h>

/*
 * @I2C_ADDRESSING_MODES
 * I2C own address mode selection macros
 */
#define I2C_ADDRMODE_7BIT       0U
#define I2C_ADDRMODE_10BIT      1U

/*
 * @I2C_TIMING_VALUES
 * I2C TIMINGR selection macros generated by STM32CubeMX
 *
 * Analog Filter: Enabled
 * Digital Filter: 0
 * Rise Time: 0 ns
 * Fall Time: 0 ns
 *
 * WARNING:
 * These values depend on the I2C kernel clock configuration.
 * If clock configuration changes, regenerate these values in CubeMX.
 */
#define I2C_TIMING_100KHZ        (0x10707DBCUL)
#define I2C_TIMING_400KHZ        (0x00602173UL)
#define I2C_TIMING_1MHZ          (0x00300B29UL)

/*
 * @I2C_STRETCH_MODES
 * I2C clock stretching selection macros for NOSTRETCH bit in CR1 register
 */
#define I2C_STRETCH_ENABLE      0U
#define I2C_STRETCH_DISABLE     1U

/*
 * @I2C_STATUS_FLAGS
 * I2C ISR flag selection macros
 */
#define I2C_FLAG_TXE        (1U << I2C_ISR_TXE)
#define I2C_FLAG_TXIS       (1U << I2C_ISR_TXIS)
#define I2C_FLAG_RXNE       (1U << I2C_ISR_RXNE)
#define I2C_FLAG_ADDR       (1U << I2C_ISR_ADDR)
#define I2C_FLAG_NACKF      (1U << I2C_ISR_NACKF)
#define I2C_FLAG_STOPF      (1U << I2C_ISR_STOPF)
#define I2C_FLAG_TC         (1U << I2C_ISR_TC)
#define I2C_FLAG_TCR        (1U << I2C_ISR_TCR)
#define I2C_FLAG_BERR       (1U << I2C_ISR_BERR)
#define I2C_FLAG_ARLO       (1U << I2C_ISR_ARLO)
#define I2C_FLAG_OVR        (1U << I2C_ISR_OVR)
#define I2C_FLAG_BUSY       (1U << I2C_ISR_BUSY)

/*
 * @I2C_RETURN_STATUS
 * I2C return status macros
 */
#define I2C_OK                 0U
#define I2C_ERROR_TIMEOUT      1U
#define I2C_ERROR_NACK         2U
#define I2C_ERROR_BERR         3U
#define I2C_ERROR_ARLO         4U
#define I2C_ERROR_OVR          5U
#define I2C_ERROR_INVALID_ARG  6U

/*
 * @I2C_TIMEOUT_VALUE
 * Software timeout value for blocking wait loops
 */
#define I2C_TIMEOUT            100000U

/*
 * @I2C_TRANSFER_DIRECTIONS
 * I2C transfer direction selection macros
 */
#define I2C_DIR_WRITE          0U
#define I2C_DIR_READ           1U

/*
 * Configuration structure for I2Cx peripheral
 */
typedef struct{
	uint32_t I2C_Timing;				/* Select from @I2C_TIMING_VALUES */
	uint16_t I2C_DeviceAddress;			/* STM32 own address. Use 0 if STM32 is master only */
	uint8_t  I2C_AddressingMode;		/* Select from @I2C_ADDRESSING_MODES */
	uint8_t  I2C_NoStretchMode;			/* Select from @I2C_STRETCH_MODES */
}I2C_Config_t;

/*
 * Handle structure for I2Cx peripheral
 */
typedef struct{
	I2C_RegDef_t *pI2Cx;
	I2C_Config_t I2C_Config;
}I2C_Handle_t;


/******************************************************************************************************
 * 								APIs Supported by This Driver
 *       For more information about the APIs, check the function definitions in stm32h7sxx_i2c_driver.c
 ******************************************************************************************************/

/*
 * Peripheral Clock Setup
 */
void I2C_PeriClockControl(I2C_RegDef_t *pI2Cx, uint8_t ENorDI);

/*
 * I2C Init - DeInit
 */
void I2C_Init(I2C_Handle_t *pI2CHandle);
void I2C_DeInit(I2C_RegDef_t *pI2Cx);

/*
 * Peripheral Control
 */
void I2C_PeripheralControl(I2C_RegDef_t *pI2Cx, uint8_t ENorDI);

/*
 * Data Send - Receive: Blocking Master APIs
 */
uint8_t I2C_MasterSendData(I2C_Handle_t *pI2CHandle, uint8_t *pTxBuffer, uint32_t Len, uint8_t SlaveAddr);
uint8_t I2C_MasterReceiveData(I2C_Handle_t *pI2CHandle, uint8_t *pRxBuffer, uint32_t Len, uint8_t SlaveAddr);

/*
 * Data Send - Receive: Blocking Slave APIs
 */
void I2C_SlaveSendData(I2C_RegDef_t *pI2Cx, uint8_t data);
uint8_t I2C_SlaveReceiveData(I2C_RegDef_t *pI2Cx);

/*
 * Memory/Register Read-Write APIs
 */
uint8_t I2C_MemWrite(I2C_Handle_t *pI2CHandle, uint8_t SlaveAddr, uint8_t RegAddr, uint8_t *pTxBuffer, uint32_t Len);
uint8_t I2C_MemRead(I2C_Handle_t *pI2CHandle, uint8_t SlaveAddr, uint8_t RegAddr, uint8_t *pRxBuffer, uint32_t Len);

/*
 * Get Flag Status
 */
uint8_t I2C_GetFlagStatus(I2C_RegDef_t *pI2Cx, uint32_t FlagName);

/*
 * IRQ Configuration and ISR Handling
 */
void I2C_IRQInterruptConfig(uint8_t IRQNumber, uint8_t ENorDI);
void I2C_IRQPriorityConfig(uint8_t IRQNumber, uint8_t IRQPriority);

#endif /* INC_STM32H7SXX_I2C_DRIVER_H_ */
