/*
 * stm32h7sxx_i2c_driver.c
 *
 *  Created on: Jun 4, 2026
 *      Author: talha
 */

#include "stm32h7sxx_i2c_driver.h"
#include <stdio.h>

#include "stm32h7sxx_i2c_driver.h"
#include <stdio.h>

/*
 * Helper prototypes
 */
static void I2C_ClearCR2TransferFields(I2C_RegDef_t *pI2Cx);
static uint8_t I2C_CheckAndClearErrors(I2C_RegDef_t *pI2Cx);
static uint8_t I2C_WaitOnFlagUntilTimeout(I2C_RegDef_t *pI2Cx, uint32_t FlagName, uint8_t DesiredStatus, uint32_t Timeout);
static void I2C_ConfigTransfer(I2C_RegDef_t *pI2Cx, uint8_t SlaveAddr, uint8_t Direction, uint32_t NBytes, uint8_t Reload, uint8_t AutoEnd);

/*
 * I2C Peripheral Clock Control
 */

/****************************************************************************
 * @fn				- I2C_PeriClockControl
 *
 * @brief			- This function enables or disables peripheral clock for I2Cx
 *
 * @param[in]		- base address of the I2C Peripheral
 * @param[in]		- ENABLE or DISABLE macros
 * @param[in]		-
 *
 * @return			- none
 *
 * @Note			- For ENorDI selection, see ENABLE / DISABLE macros in stm32h7sxx.h.
 * 					-
 *
 */
void I2C_PeriClockControl(I2C_RegDef_t *pI2Cx, uint8_t ENorDI){
    if (ENorDI == ENABLE){
        if (pI2Cx == I2C1) {
            I2C1_PCLK_EN();
        } else if (pI2Cx == I2C2) {
            I2C2_PCLK_EN();
        } else if (pI2Cx == I2C3) {
            I2C3_PCLK_EN();
        }
    }else if(ENorDI == DISABLE) {
        if (pI2Cx == I2C1) {
            I2C1_PCLK_DI();
        } else if (pI2Cx == I2C2) {
            I2C2_PCLK_DI();
        } else if (pI2Cx == I2C3) {
            I2C3_PCLK_DI();
        }
    } else{
    	//Return error
    }
}

/*
 * I2C Init - DeInıt
 */
/****************************************************************************
 * @fn              - I2C_Init
 *
 * @brief           - This function initializes the I2C peripheral
 *
 * @param[in]       - pI2CHandle: I2C handle structure with base address
 *                    and configuration
 *
 * @return          - none
 *
 * @Note            - For I2C_Timing, I2C_AddressingMode and I2C_NoStretchMode selections,
 *                    see @I2C_TIMING_VALUES, @I2C_ADDRESSING_MODES and @I2C_STRETCH_MODES.
 *
 *                  - I2C timing, filter and own address configuration must be
 *                    done while PE = 0.
 *
 *                  - I2C_DeviceAddress is the STM32 own address.
 *                    If STM32 is used only as master, this can be 0.
 *                    If STM32 is used as slave, set a valid own address.
 *
 */
void I2C_Init(I2C_Handle_t *pI2CHandle){
    uint32_t tempreg = 0;

    if ((pI2CHandle == NULL) || (pI2CHandle->pI2Cx == NULL)){
        // Invalid handle
        return;
    }

    //Enable peripheral clock
    I2C_PeriClockControl(pI2CHandle->pI2Cx, ENABLE);

    /*
     * Disable I2C peripheral before configuration (TIMINGR, filters and own address must be configured while PE = 0.)
     */
    I2C_PeripheralControl(pI2CHandle->pI2Cx, DISABLE);
    while (pI2CHandle->pI2Cx->CR1 & (1U << I2C_CR1_PE));

    /*
     * Configure filters
     * DNF[3:0] = 0000 : Digital filter disabled
     * ANFOFF   = 0    : Analog filter enabled
     */
    pI2CHandle->pI2Cx->CR1 &= ~(0xFU << I2C_CR1_DNF);
    pI2CHandle->pI2Cx->CR1 &= ~(1U << I2C_CR1_ANFOFF);

    /*
     * Disable target byte control mode for basic I2C operation.
     * SBC is only needed for byte-by-byte ACK control in target receiver mode.
     */
    pI2CHandle->pI2Cx->CR1 &= ~(1U << I2C_CR1_SBC);

    //Configure TIMINGR. This value must be generated by CubeMX
    pI2CHandle->pI2Cx->TIMINGR = pI2CHandle->I2C_Config.I2C_Timing;

    //Configure NOSTRETCH
    if (pI2CHandle->I2C_Config.I2C_NoStretchMode == I2C_STRETCH_DISABLE){
		pI2CHandle->pI2Cx->CR1 |= (1U << I2C_CR1_NOSTRETCH);
	} else{
		pI2CHandle->pI2Cx->CR1 &= ~(1U << I2C_CR1_NOSTRETCH);
	}

    /*
     * Disable hardware timeout feature for normal I2C usage
     * For Timeout settings see @fn - I2C_WaitOnFlagUntilTimeout in HELPERS section
     */
    pI2CHandle->pI2Cx->TIMEOUTR = 0U;

    /*
     * Configure own address
     *
     * Own address is only needed when STM32 works as an I2C slave/target.
     *
     * If I2C_DeviceAddress == 0:
     *      Own address is not configured.
     *
     * If I2C_DeviceAddress != 0:
     *      OAR1 is configured and enabled.
     */
    pI2CHandle->pI2Cx->OAR1 = 0U;

    if (pI2CHandle->I2C_Config.I2C_DeviceAddress != 0U){
        if (pI2CHandle->I2C_Config.I2C_AddressingMode == I2C_ADDRMODE_7BIT){
        	// 7-bit own address mode
            tempreg |= ((uint32_t)(pI2CHandle->I2C_Config.I2C_DeviceAddress & 0x7FU) << 1U);
        } else{
            // 10-bit own address mode
            tempreg |= ((uint32_t)(pI2CHandle->I2C_Config.I2C_DeviceAddress & 0x3FFU) << I2C_OAR1_OA1);
            tempreg |= (1U << I2C_OAR1_OA1MODE);
        }

        //Enable own address 1
        tempreg |= (1U << I2C_OAR1_OA1EN);

        pI2CHandle->pI2Cx->OAR1 = tempreg;
    }

    //Enable I2C peripheral
    I2C_PeripheralControl(pI2CHandle->pI2Cx, ENABLE);
}

/****************************************************************************
 * @fn				- I2C_DeInit
 *
 * @brief			- This function resets the selected I2C peripheral
 *
 * @param[in]		- pI2Cx: base address of the I2C peripheral
 * @param[in]		-
 * @param[in]		-
 *
 * @return			- none
 *
 * @Note			- Reset bit must be set and then cleared.
 * 					- If the bit stays set, the peripheral remains in reset.
 *					-
 *
 */
void I2C_DeInit(I2C_RegDef_t *pI2Cx) {
	if (pI2Cx == I2C1){
		//Reset all I2C1 registers
		RCC->APB1RSTR1 |=  (1U << 21);
        RCC->APB1RSTR1 &= ~(1U << 21);
    } else if (pI2Cx == I2C2){
    	//Reset all I2C2 registers
        RCC->APB1RSTR1 |=  (1U << 22);
        RCC->APB1RSTR1 &= ~(1U << 22);
    } else if (pI2Cx == I2C3){
    	//Reset all I2C3 registers
        RCC->APB1RSTR1 |=  (1U << 23);
        RCC->APB1RSTR1 &= ~(1U << 23);
    }
}

/*
 * Peripheral Control
 */
/****************************************************************************
 * @fn				- I2C_PeripheralControl
 *
 * @brief			- This function enables or disables I2Cx peripheral
 *
 * @param[in]		- I2C Base address
 * @param[in]		- ENABLE or DISABLE macros
 * @param[in]		-
 *
 * @return			- none
 *
 * @Note			- For ENorDI selection, see ENABLE / DISABLE macros in stm32h7sxx.h.
 * 					-
 *
 */
void I2C_PeripheralControl(I2C_RegDef_t *pI2Cx, uint8_t ENorDI){
	if(ENorDI == ENABLE){
		pI2Cx->CR1 |= (SET << I2C_CR1_PE);
	} else if(ENorDI == DISABLE){
		pI2Cx->CR1 &= ~(SET << I2C_CR1_PE);
	} else{
		//Return error
	}
}

/*
 * Data Send - Receive: Blocking Master APIs
 */
/****************************************************************************
 * @fn              - I2C_MasterSendData
 *
 * @brief           - This function sends data in master mode using blocking method
 *
 * @param[in]       - pI2CHandle: I2C handle structure
 * @param[in]       - pTxBuffer: pointer to transmit buffer
 * @param[in]       - Len: number of bytes to transmit
 * @param[in]       - SlaveAddr: 7-bit slave address
 *
 * @return          - I2C_OK or @I2C_RETURN_STATUS error macros
 *
 * @Note            - This function supports transfers longer than 255 bytes using RELOAD mode.
 *
 */
uint8_t I2C_MasterSendData(I2C_Handle_t *pI2CHandle, uint8_t *pTxBuffer, uint32_t Len, uint8_t SlaveAddr){
	I2C_RegDef_t *pI2Cx = NULL;
	uint32_t bytes_to_send;
	uint8_t status;

	//Argument check
    if ((pI2CHandle == NULL) || (pI2CHandle->pI2Cx == NULL) || (pTxBuffer == NULL) || (Len == 0U)){
        return I2C_ERROR_INVALID_ARG;
    }

	pI2Cx = pI2CHandle->pI2Cx;

	status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
										I2C_FLAG_BUSY,
										FLAG_RESET,
										I2C_TIMEOUT);

	if(status != I2C_OK){
		return status;
	}

	bytes_to_send = (Len > 255U) ? 255U : Len;

    I2C_ConfigTransfer(pI2Cx,
                       SlaveAddr,
                       I2C_DIR_WRITE,
                       bytes_to_send,
                       (Len > 255U) ? ENABLE : DISABLE,
                       (Len > 255U) ? DISABLE : ENABLE);

	//Generate START
	pI2Cx->CR2 |= (1U << I2C_CR2_START);

	//Send bytes
	while(Len > 0U){
	   status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
											I2C_FLAG_TXIS,
											FLAG_SET,
											I2C_TIMEOUT);

		if(status != I2C_OK){
			return status;
		}

		//Send the message to TX Data Register
		pI2Cx->TXDR = *pTxBuffer;
		pTxBuffer++;
		Len--;
		bytes_to_send--;

		if((bytes_to_send == 0U) && (Len > 0U)){
            status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                                I2C_FLAG_TCR,
                                                FLAG_SET,
                                                I2C_TIMEOUT);
    		if(status != I2C_OK){
    			return status;
    		}

            bytes_to_send = (Len > 255U) ? 255U : Len;

            pI2Cx->CR2 &= ~(0xFFU << I2C_CR2_NBYTES);
            pI2Cx->CR2 |= ((bytes_to_send & 0xFFU) << I2C_CR2_NBYTES);

            if (Len > 255U){
                pI2Cx->CR2 |= (1U << I2C_CR2_RELOAD);
                pI2Cx->CR2 &= ~(1U << I2C_CR2_AUTOEND);
            } else{
                pI2Cx->CR2 &= ~(1U << I2C_CR2_RELOAD);
                pI2Cx->CR2 |= (1U << I2C_CR2_AUTOEND);
            }
		}
	}

	//Wait until STOP
    status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                        I2C_FLAG_STOPF,
                                        FLAG_SET,
                                        I2C_TIMEOUT);
    if (status != I2C_OK){
        return status;
    }

	//Clear Stop Flag
	pI2Cx->ICR |= (1U << I2C_ICR_STOPCF);

	return I2C_OK;
}

/****************************************************************************
 * @fn              - I2C_MasterReceiveData
 *
 * @brief           - This function receives data in master mode using blocking method
 *
 * @param[in]       - pI2CHandle: I2C handle structure
 * @param[in]       - pRxBuffer: pointer to receive buffer
 * @param[in]       - Len: number of bytes to receive
 * @param[in]       - SlaveAddr: 7-bit slave address
 *
 * @return          - I2C_OK or @I2C_RETURN_STATUS error macros
 *
 * @Note            - This function supports transfers longer than 255 bytes using RELOAD mode.
 *
 */
uint8_t I2C_MasterReceiveData(I2C_Handle_t *pI2CHandle, uint8_t *pRxBuffer, uint32_t Len, uint8_t SlaveAddr){
    I2C_RegDef_t *pI2Cx;
	uint32_t bytes_to_read;
	uint8_t status;

	//Argument check
	if ((pI2CHandle == NULL) || (pI2CHandle->pI2Cx == NULL) || (pRxBuffer == NULL) || (Len == 0U)) {
		return I2C_ERROR_INVALID_ARG;
	}

	pI2Cx = pI2CHandle->pI2Cx;

	status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
										I2C_FLAG_BUSY,
										FLAG_RESET,
										I2C_TIMEOUT);
	if (status != I2C_OK){
		return status;
	}

	bytes_to_read = (Len > 255U) ? 255U : Len;

	I2C_ConfigTransfer(pI2Cx,
					   SlaveAddr,
					   I2C_DIR_READ,
					   bytes_to_read,
					   (Len > 255U) ? ENABLE : DISABLE,
					   (Len > 255U) ? DISABLE : ENABLE);

	pI2Cx->CR2 |= (1U << I2C_CR2_START);

	//Read bytes
	while (Len > 0U){
		status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
											I2C_FLAG_RXNE,
											FLAG_SET,
											I2C_TIMEOUT);
		if (status != I2C_OK){
			return status;
		}

		*pRxBuffer = (uint8_t)pI2Cx->RXDR;
		pRxBuffer++;
		Len--;
		bytes_to_read--;

		if ((bytes_to_read == 0U) && (Len > 0U)){
			status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
												I2C_FLAG_TCR,
												FLAG_SET,
												I2C_TIMEOUT);
			if (status != I2C_OK){
				return status;
			}

			bytes_to_read = (Len > 255U) ? 255U : Len;

			pI2Cx->CR2 &= ~(0xFFU << I2C_CR2_NBYTES);
			pI2Cx->CR2 |= ((bytes_to_read & 0xFFU) << I2C_CR2_NBYTES);

			if (Len > 255U){
				pI2Cx->CR2 |= (1U << I2C_CR2_RELOAD);
				pI2Cx->CR2 &= ~(1U << I2C_CR2_AUTOEND);
			} else{
				pI2Cx->CR2 &= ~(1U << I2C_CR2_RELOAD);
				pI2Cx->CR2 |= (1U << I2C_CR2_AUTOEND);
			}
		}
	}

	status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
										I2C_FLAG_STOPF,
										FLAG_SET,
										I2C_TIMEOUT);
	if (status != I2C_OK){
		return status;
	}

	pI2Cx->ICR |= (1U << I2C_ICR_STOPCF);

	return I2C_OK;
}

/*
 * Data Send - Receive: Blocking Slave APIs
 */
/****************************************************************************
 * @fn              - I2C_SlaveSendData
 *
 * @brief           - This function writes one byte to TXDR in slave mode
 *
 * @param[in]       - pI2Cx: base address of the I2C peripheral
 * @param[in]       - data: byte to be transmitted
 *
 * @return          - none
 *
 * @Note            - Usually called when TXIS flag is set.
 *
 */
void I2C_SlaveSendData(I2C_RegDef_t *pI2Cx, uint8_t data){
	if(pI2Cx == NULL){
		//Return error
		return;
	}

	//Send bytes
	pI2Cx->TXDR = data;
}

/****************************************************************************
 * @fn              - I2C_SlaveReceiveData
 *
 * @brief           - This function reads one byte from RXDR in slave mode
 *
 * @param[in]       - pI2Cx: base address of the I2C peripheral
 *
 * @return          - received byte
 *
 * @Note            - Usually called when RXNE flag is set.
 *
 */
uint8_t I2C_SlaveReceiveData(I2C_RegDef_t *pI2Cx){
	if(pI2Cx == NULL){
		//Return error
		return 0;
	}

	return(uint8_t)pI2Cx->RXDR;
}

/*
 * Memory/Register Read-Write APIs
 */
/****************************************************************************
 * @fn              - I2C_MemWrite
 *
 * @brief           - This function writes data to a target register/memory address
 *
 * @param[in]       - pI2CHandle: I2C handle structure
 * @param[in]       - SlaveAddr: 7-bit slave address
 * @param[in]       - RegAddr: target register address
 * @param[in]       - pTxBuffer: pointer to data buffer
 * @param[in]       - Len: number of data bytes
 *
 * @return          - I2C_OK or @I2C_RETURN_STATUS error macros
 *
 * @Note            - This function supports 8-bit register addresses.
 *
 */
uint8_t I2C_MemWrite(I2C_Handle_t *pI2CHandle, uint8_t SlaveAddr, uint8_t RegAddr, uint8_t *pTxBuffer, uint32_t Len){
    I2C_RegDef_t *pI2Cx;
    uint32_t total_len;
    uint32_t bytes_to_send;
    uint8_t reg_sent = 0U;
    uint8_t status;

    //Argument check
    if ((pI2CHandle == NULL) || (pI2CHandle->pI2Cx == NULL) || (pTxBuffer == NULL) || (Len == 0U)) {
        return I2C_ERROR_INVALID_ARG;
    }

    pI2Cx = pI2CHandle->pI2Cx;

    total_len = Len + 1U;   // register address byte + data bytes

    status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                        I2C_FLAG_BUSY,
                                        FLAG_RESET,
                                        I2C_TIMEOUT);
    if (status != I2C_OK){
        return status;
    }

    bytes_to_send = (total_len > 255U) ? 255U : total_len;

    I2C_ConfigTransfer(pI2Cx,
                       SlaveAddr,
                       I2C_DIR_WRITE,
                       bytes_to_send,
                       (total_len > 255U) ? ENABLE : DISABLE,
                       (total_len > 255U) ? DISABLE : ENABLE);

    pI2Cx->CR2 |= (1U << I2C_CR2_START);

    while (total_len > 0U){
        status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                            I2C_FLAG_TXIS,
                                            FLAG_SET,
                                            I2C_TIMEOUT);
        if (status != I2C_OK){
            return status;
        }

        if (reg_sent == 0U){
            pI2Cx->TXDR = RegAddr;
            reg_sent = 1U;
        } else{
            pI2Cx->TXDR = *pTxBuffer;
            pTxBuffer++;
        }

        total_len--;
        bytes_to_send--;

        if ((bytes_to_send == 0U) && (total_len > 0U)){
            status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                                I2C_FLAG_TCR,
                                                FLAG_SET,
                                                I2C_TIMEOUT);
            if (status != I2C_OK){
                return status;
            }

            bytes_to_send = (total_len > 255U) ? 255U : total_len;

            pI2Cx->CR2 &= ~(0xFFU << I2C_CR2_NBYTES);
            pI2Cx->CR2 |= ((bytes_to_send & 0xFFU) << I2C_CR2_NBYTES);

            if (total_len > 255U){
                pI2Cx->CR2 |= (1U << I2C_CR2_RELOAD);
                pI2Cx->CR2 &= ~(1U << I2C_CR2_AUTOEND);
            } else{
                pI2Cx->CR2 &= ~(1U << I2C_CR2_RELOAD);
                pI2Cx->CR2 |= (1U << I2C_CR2_AUTOEND);
            }
        }
    }

    status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                        I2C_FLAG_STOPF,
                                        FLAG_SET,
                                        I2C_TIMEOUT);
    if (status != I2C_OK){
        return status;
    }

    pI2Cx->ICR |= (1U << I2C_ICR_STOPCF);

    return I2C_OK;
}

/****************************************************************************
 * @fn              - I2C_MemRead
 *
 * @brief           - This function reads data from a target register/memory address
 *
 * @param[in]       - pI2CHandle: I2C handle structure
 * @param[in]       - SlaveAddr: 7-bit slave address
 * @param[in]       - RegAddr: target register address
 * @param[in]       - pRxBuffer: pointer to receive buffer
 * @param[in]       - Len: number of bytes to read
 *
 * @return          - none
 *
 * @Note            - This function uses repeated START.
 *                    It supports 8-bit register addresses
 *
 */
uint8_t I2C_MemRead(I2C_Handle_t *pI2CHandle, uint8_t SlaveAddr, uint8_t RegAddr, uint8_t *pRxBuffer, uint32_t Len){
    I2C_RegDef_t *pI2Cx;
    uint32_t bytes_to_read;
    uint8_t status;

    if ((pI2CHandle == NULL) || (pI2CHandle->pI2Cx == NULL) || (pRxBuffer == NULL) || (Len == 0U)){
        return I2C_ERROR_INVALID_ARG;
    }

    pI2Cx = pI2CHandle->pI2Cx;

    status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                        I2C_FLAG_BUSY,
                                        FLAG_RESET,
                                        I2C_TIMEOUT);
    if (status != I2C_OK){
        return status;
    }

    /*
     * Send register address.
     * AUTOEND = 0, repeated START without STOP
     */
    I2C_ConfigTransfer(pI2Cx,
                       SlaveAddr,
                       I2C_DIR_WRITE,
                       1U,
                       DISABLE,
                       DISABLE);

    pI2Cx->CR2 |= (1U << I2C_CR2_START);

    status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                        I2C_FLAG_TXIS,
                                        FLAG_SET,
                                        I2C_TIMEOUT);
    if (status != I2C_OK){
        return status;
    }

    pI2Cx->TXDR = RegAddr;

    /*
     * TC means the register-address write phase is complete,
     */
    status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                        I2C_FLAG_TC,
                                        FLAG_SET,
                                        I2C_TIMEOUT);
    if (status != I2C_OK){
        return status;
    }

    /*
     * Read data using RELOAD if Len > 255.
     */
    bytes_to_read = (Len > 255U) ? 255U : Len;

    I2C_ConfigTransfer(pI2Cx,
                       SlaveAddr,
                       I2C_DIR_READ,
                       bytes_to_read,
                       (Len > 255U) ? ENABLE : DISABLE,
                       (Len > 255U) ? DISABLE : ENABLE);

    pI2Cx->CR2 |= (1U << I2C_CR2_START);

    while (Len > 0U){
        status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                            I2C_FLAG_RXNE,
                                            FLAG_SET,
                                            I2C_TIMEOUT);
        if (status != I2C_OK){
            return status;
        }

        *pRxBuffer = (uint8_t)pI2Cx->RXDR;
        pRxBuffer++;
        Len--;
        bytes_to_read--;

        if ((bytes_to_read == 0U) && (Len > 0U)){
            status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                                I2C_FLAG_TCR,
                                                FLAG_SET,
                                                I2C_TIMEOUT);
            if (status != I2C_OK){
                return status;
            }

            bytes_to_read = (Len > 255U) ? 255U : Len;

            pI2Cx->CR2 &= ~(0xFFU << I2C_CR2_NBYTES);
            pI2Cx->CR2 |= ((bytes_to_read & 0xFFU) << I2C_CR2_NBYTES);

            if (Len > 255U){
                pI2Cx->CR2 |= (1U << I2C_CR2_RELOAD);
                pI2Cx->CR2 &= ~(1U << I2C_CR2_AUTOEND);
            } else{
                pI2Cx->CR2 &= ~(1U << I2C_CR2_RELOAD);
                pI2Cx->CR2 |= (1U << I2C_CR2_AUTOEND);
            }
        }
    }

    status = I2C_WaitOnFlagUntilTimeout(pI2Cx,
                                        I2C_FLAG_STOPF,
                                        FLAG_SET,
                                        I2C_TIMEOUT);
    if (status != I2C_OK){
        return status;
    }

    pI2Cx->ICR |= (1U << I2C_ICR_STOPCF);

    return I2C_OK;
}

/*
 * Get Flag Status
 */
/****************************************************************************
 * @fn              - I2C_GetFlagStatus
 *
 * @brief           - This function checks whether a specific I2C flag is set
 *
 * @param[in]       - pI2Cx: base address of the I2C peripheral
 * @param[in]       - FlagName: flag macro to be checked
 *
 * @return          - FLAG_SET or FLAG_RESET
 *
 * @Note            - For FlagName selection, see @I2C_STATUS_FLAGS macros.
 *
 */
uint8_t I2C_GetFlagStatus(I2C_RegDef_t *pI2Cx, uint32_t FlagName){
	if(pI2Cx == NULL){
		return FLAG_RESET;
	}

	if(pI2Cx->ISR & FlagName){
		return FLAG_SET;
	}

	return FLAG_RESET;
}

/*
 * IRQ Configuration and ISR Handling
 */
/****************************************************************************
 * @fn              - I2C_IRQInterruptConfig
 *
 * @brief           - This function enables or disables IRQ in NVIC
 *
 * @param[in]       - IRQNumber: IRQ number
 * @param[in]       - ENorDI: ENABLE or DISABLE
 *
 * @return          - none
 *
 * @Note            - For ENorDI selection, see ENABLE / DISABLE macros in stm32h7sxx.h.
 *
 */
void I2C_IRQInterruptConfig(uint8_t IRQNumber, uint8_t ENorDI){
	if(ENorDI == ENABLE){
		NVIC_ISER[IRQNumber / 32U] |= (1U << IRQNumber % 32U);
	}else if(ENorDI == DISABLE){
		NVIC_ICER[IRQNumber / 32U] |= (1U << IRQNumber % 32U);
	}else{
		//Invalid
		return;
	}
}

/****************************************************************************
 * @fn              - I2C_IRQPriorityConfig
 *
 * @brief           - This function configures IRQ priority
 *
 * @param[in]       - IRQNumber: IRQ number
 * @param[in]       - IRQPriority: priority value
 *
 * @return          - none
 *
 * @Note            - IRQPriority must match implemented NVIC priority bits.
 *
 */
void I2C_IRQPriorityConfig(uint8_t IRQNumber, uint8_t IRQPriority){
    uint8_t iprx = IRQNumber / 4U;
    uint8_t iprx_section = IRQNumber % 4U;

    uint8_t shift_amount = (8U * iprx_section) + (8U - NVIC_PRIO_BITS_IMPLEMENTED);

    NVIC_IPR[iprx] &= ~(0xFU << shift_amount);
    NVIC_IPR[iprx] |= ((IRQPriority & 0xFU) << shift_amount);
}

/*
 * Helper Functions
 */

/*@fn				- I2C_ClearCR2TransferFields
 *@note				- CR2 Transfer Fields Clearing Function
 */
static void I2C_ClearCR2TransferFields(I2C_RegDef_t *pI2Cx){
    pI2Cx->CR2 &= ~((0x3FFU << I2C_CR2_SADD)    |
                    (1U    << I2C_CR2_RD_WRN)  |
                    (1U    << I2C_CR2_ADD10)   |
                    (0xFFU << I2C_CR2_NBYTES)  |
                    (1U    << I2C_CR2_RELOAD)  |
                    (1U    << I2C_CR2_AUTOEND));
}

/*@fn				- I2C_CheckAndClearErrors
 *@note				- I2C Error Check-Clear
 */
static uint8_t I2C_CheckAndClearErrors(I2C_RegDef_t *pI2Cx){
    if (I2C_GetFlagStatus(pI2Cx, I2C_FLAG_NACKF) == FLAG_SET){
        pI2Cx->ICR |= (1U << I2C_ICR_NACKCF);
        return I2C_ERROR_NACK;
    }

    if (I2C_GetFlagStatus(pI2Cx, I2C_FLAG_BERR) == FLAG_SET){
        pI2Cx->ICR |= (1U << I2C_ICR_BERRCF);
        return I2C_ERROR_BERR;
    }

    if (I2C_GetFlagStatus(pI2Cx, I2C_FLAG_ARLO) == FLAG_SET){
        pI2Cx->ICR |= (1U << I2C_ICR_ARLOCF);
        return I2C_ERROR_ARLO;
    }

    if (I2C_GetFlagStatus(pI2Cx, I2C_FLAG_OVR) == FLAG_SET){
        pI2Cx->ICR |= (1U << I2C_ICR_OVRCF);
        return I2C_ERROR_OVR;
    }

    return I2C_OK;
}

/*@fn				- I2C_WaitOnFlagUntilTimeout
 *@note				- I2C Timeout Function
 */
static uint8_t I2C_WaitOnFlagUntilTimeout(I2C_RegDef_t *pI2Cx, uint32_t FlagName, uint8_t DesiredStatus, uint32_t Timeout){
    uint8_t error_status;

    while (I2C_GetFlagStatus(pI2Cx, FlagName) != DesiredStatus){
        error_status = I2C_CheckAndClearErrors(pI2Cx);
        if (error_status != I2C_OK){
            return error_status;
        }

        if (Timeout-- == 0U){
            return I2C_ERROR_TIMEOUT;
        }
    }

    return I2C_OK;
}

/*@fn				- I2C_ConfigTransfer
 *@note				- I2C Configuration Transfer Function
 *					  For Direction selection, see @I2C_TRANSFER_DIRECTIONS macros.
 */
static void I2C_ConfigTransfer(I2C_RegDef_t *pI2Cx, uint8_t SlaveAddr, uint8_t Direction, uint32_t NBytes, uint8_t Reload, uint8_t AutoEnd) {
    I2C_ClearCR2TransferFields(pI2Cx);

    // 7-bit slave address (e.g: 0x3C, 0x68): Hardware expects it in SADD[7:1].
    // No 10-bit address support (05.06.2026)
    pI2Cx->CR2 |= ((uint32_t)(SlaveAddr & 0x7FU) << 1U);

    if (Direction == I2C_DIR_READ){
        pI2Cx->CR2 |= (1U << I2C_CR2_RD_WRN);
    } else if (Direction == I2C_DIR_WRITE){
        pI2Cx->CR2 &= ~(1U << I2C_CR2_RD_WRN);
    } else{
    	//Invalid config
    	return;
    }

    pI2Cx->CR2 |= ((NBytes & 0xFFU) << I2C_CR2_NBYTES);

    if (Reload == ENABLE){
        pI2Cx->CR2 |= (1U << I2C_CR2_RELOAD);
    }

    if (AutoEnd == ENABLE){
        pI2Cx->CR2 |= (1U << I2C_CR2_AUTOEND);
    }
}
/*
 * End of Helper Functions
 */
